<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Display.aspx.cs" Inherits="Display" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Autogenerated Test - CATB</title>
    <link href="css/style.css" rel="stylesheet" type="text/css" />
</head>
<body>

    <form id="form2" runat="server" method="post">
<div id="wrapper">
  <div id="content">
      <div id="contentarea">
         <asp:Button ID="Button1" runat="server" Text="show" 
            onclick="Button1_Click"  Visible="false"/>
        <asp:Button ID="Button2" runat="server" Text="retrievedata" 
            onclick="Button2_Click" Visible="false"/>
        <asp:Button ID="Button3" runat="server" onclick="Button3_Click" Text="student" Visible="false"/>
        <asp:Button ID="Button4" 
            runat="server" onclick="Button4_Click" Text="fellow" Visible="false"/>
        
 <div id="output" runat="server"></div>
    </div>
    </div>
</form>
</body>

</html>
